### ISSUE TITLE
Stackblitz is stuck with "Compiling application & starting dev server" when trying to use Angular Ivy

### ISSUE THREAD

**Issue by Maximaximum** [stackblitz/core#1227]
Just check this link:
https://stackblitz.com/edit/primeng-strict-template-checks-ivy?file=src/app/app.component.html

It's just the demo stackblitz Angular project switched to Ivy. The recompilation take forever

**Comment by Maximaximum** [comment]
It seems like the issue is that there's a compilation error. However, stackblitz users have no way to see the compilation errors

**Comment by EricSimons** [comment]
This has now been fixed, in the sense that we show the error message :) Specifically, primeng seems to fail out with the ngcc process. We're investigating root cause on our end and will circle back once we have it sorted 👍

**Comment by Maximaximum** [comment]
Well, would you mind to let me know where can I see the error message?

And yes, I was trying to use stackblitz to reproduce a primeng compilation problem in order to be able to open an issue at primeng. But I'm unable to do that, since stackblitz simply hangs without providing the compilation error output :)

**Comment by EricSimons** [comment]
We had to roll back the change unfortunately due to a bug- should have this online again sometime today and will circle back!

**Comment by EricSimons** [comment]
Now live! Lmk if you see the error message now :)

**Comment by Maximaximum** [comment]
Hm, yes, now I see an error message saying `Error in ~/src/main.ts
ngcc failed to run on primeng@9.0.6.`.

Now I realize that I haven't even set up the code to reproduce my original primeng issue!

In the given stackblitz project, `primeng` is not even imported anywhere. It's just listed in `package.json` and therefore installed. Then, `ngcc` tries to compile it and obviously fails. But I wonder why? Is it a `primeng` bug or a `stackblitz` one? I don't seem to have this issue in my enterprise project.

It seems like this issue should not be closed yet, it needs to be actually fixed :)

**Comment by arikanorh** [comment]
I'm having this problem constantly recently. It just does'nt give any error. But stuck at compile

**Comment by Maximaximum** [comment]
Hm, in my case the console does not seem to have any meaningful error messages, so I still don't know what's the actual issue :(

**Comment by EricSimons** [comment]
Hey all- can you try again now and lmk if anything is still breaking? We've pushed a handful of fixes the past few weeks that _should_ address these

**Comment by arikanorh** [comment]
All is well for me

**Comment by Maximaximum** [comment]
@EricSimons in my case, nothing new. Still the same `Error in ~/src/main.ts ngcc failed to run on primeng@9.0.6.` message

**Comment by Maximaximum** [comment]
@EricSimons any progress here?
