### ISSUE TITLE
Code and console not showing up in Safari 13.1.1

### ISSUE THREAD

**Issue by loreanvictor** [stackblitz/core#1399]
This is what I get when I open [this link](https://stackblitz.com/edit/react-callbag-streams-demo-4) (or any other project):

<img width="1440" alt="Screen Shot 2021-03-09 at 10 29 36 AM" src="https://user-images.githubusercontent.com/13572283/110449586-a084ca80-80c2-11eb-9006-3f4838419d27.png">

☝️as you can see the console and the code sections aren't loading. There are no errors in the console and the container div is simply empty (in Chrome monaco-editor is mounted inside that div).

I have reproduced this on Safari 13.1.1 and on macOS 10.15.5. It used to work with the same version of Safari about two weeks ago (to the best of my recollection), so I suspect an update in between must have caused the issue.

**Comment by EricSimons** [comment]
Thanks for posting this- I think the new builds of Monaco may be breaking previous version of Safari. I just opened up SB using Safari 14 and it seems to work. Can you try updating Safari (or using Chrome/Edge/Firefox) and lmk if you continue to see this issue?

**Comment by EricSimons** [comment]
Awesome, thanks for confirming. One thing that would also be helpful to know- does Monaco render for you properly on their official docs pages? https://microsoft.github.io/monaco-editor/index.html

**Comment by loreanvictor** [comment]
Good point! Nope, same issue (the container div is empty while it is populated on other browsers). It is notable that there is an error on Monaco website console which seems to be causing the issue (basically Safari picks a syntax error in one of the methods of what appears to be the minified editor class, which is stopping the editor script from executing).

**Comment by EricSimons** [comment]
Yep looks like this is an upstream issue with monaco (https://github.com/microsoft/monaco-editor/issues/2345)

I'm circling back with our team now to see what sensible next steps would be.

**Comment by SamVerschueren** [comment]
We might have found a fix. Will keep everyone posted on the status! Thanks for reporting.

**Comment by SamVerschueren** [comment]
@loreanvictor We released a new update which should solve the Safari issue (hopefully). Can you verify if it works for you?

**Comment by Controlhaus** [comment]
> @loreanvictor We released a new update which should solve the Safari issue (hopefully). Can you verify if it works for you?

Thanks for working on this. It is still not working on my site though with Safari 13.1.2: https://learnavprogramming.com/html5-part-i/

**Comment by loreanvictor** [comment]
@SamVerschueren unfortunately it has gone worse 😅 So right now the editor page loads for a second and then vanishes away:

![ezgif com-video-to-gif-8](https://user-images.githubusercontent.com/13572283/112278914-9c8ca700-8c83-11eb-8e83-2c90be2e4dc2.gif)

This does not seem to be a styling issue, but rather some script breaking during rendering and cleaning the DOM on cleanup, since this is the HTML of the page:

```html
<!DOCTYPE html>
<html lang="en" class="theme-dark">
  <head>...</head>
  <body tabindex="-1">
    <script>Analytics.page();</script>
    <script type="application/json" class="js-react-on-rails-component" data-component-name="App" data-dom-id="App-react-component-a92fda1c-5ef6-43e0-972c-14a2d27e11db">{}</script>
    <div id="App-react-component-a92fda1c-5ef6-43e0-972c-14a2d27e11db"></div>
    <style>
      body {
        background: #333333;
      }
    </style>
    <script type="application/json" data-js-react-on-rails-store="appStore">...</script>
  </body>
</html>
```
(i.e. the `div#App-react-component-...` is empty and has no children).

Also these are the logs in the console, in case that helps:

<img width="1440" alt="Screen Shot 2021-03-24 at 9 39 47 AM" src="https://user-images.githubusercontent.com/13572283/112280179-05c0ea00-8c85-11eb-8625-0fa577e61da8.png">

**Comment by loreanvictor** [comment]
Also if it helps: on an embed, where the code is open by default and the preview is not, this error does not occur. The code is not loaded (as before), but this "new" issue happens when I switch to either "Preview" or "Both" (tested on the link provided by @Controlhaus):

![ezgif com-video-to-gif-9](https://user-images.githubusercontent.com/13572283/112282070-08bcda00-8c87-11eb-9bf3-a0a77ca25db7.gif)

These are the errors in the console before "Preview" or "Both" are opened:

<img width="1440" alt="Screen Shot 2021-03-24 at 9 55 52 AM" src="https://user-images.githubusercontent.com/13572283/112282498-77019c80-8c87-11eb-87ef-4b995e305093.png">

And these errors occur after I click on either one of them:

<img width="1440" alt="Screen Shot 2021-03-24 at 9 56 20 AM" src="https://user-images.githubusercontent.com/13572283/112282569-8680e580-8c87-11eb-955e-f8bf682e276c.png">

**Comment by Controlhaus** [comment]
Please keep in mind that there are multiple Stackblitz embeds on [that page]( https://learnavprogramming.com/html5-part-i/). I've seen that change the behaviour of the preview.

**Comment by loreanvictor** [comment]
> Please keep in mind that there are multiple Stackblitz embeds on that page. I've seen that change the behaviour of the preview.

To be sure, I loaded only [a single one](https://stackblitz.com/edit/hello-world-lavp?embed=1&file=index.html&hideNavigation=1&view=editor).

**Comment by SamVerschueren** [comment]
We will try to resolve this on our end but can't give a clear timing as when we are able to fix it. It doesn't help that Monaco doesn't really care about Safari 13 bugs...

We are planning to rollout some updates for the editor first with some drastic DX improvements and then we will try to address the Safari issues.

**Comment by loreanvictor** [comment]
Could I suggest, if it doesn't consume much time, to also roll back [this fix](https://github.com/stackblitz/core/issues/1399#issuecomment-805554114) in the meanwhile? Before this fix at least embeds in "Preview" mode were usable.

**Comment by SamVerschueren** [comment]
Found the culprit and created a PR to get the fix deployed. Will keep you guys posted on the progress. Will probably be deployed later today.
