### ISSUE TITLE
Angular 13 support

### ISSUE THREAD

**Issue by spicemix** [stackblitz/core#1657]
### **Description of Bug**

Can't successfully update a project to Angular 13 (and doesn't seem to be any easy way to roll back to 12, unless you use git or something).

### **Steps to Reproduce**

1. Create a new Angular (Typescript) project
2. Click on `Update all deps to latest` circular arrow thing top right corner of the `DEPENDENCIES` list

-> Angular 13.0 is partly installed
-> Errors result

### **Expected Behavior**

We update to Angular 13 and everything works.

Or, you block updating dependencies you don't support yet.

### **Screenshots/Screencast**

```
Error in ~/src/main.ts
ngcc failed to run on rxjs@7.4.0, @angular/compiler@13.0.0, @angular/common@13.0.0, @angular/core@13.0.0, @angular/platform-browser@13.0.0, @angular/animations@13.0.0, @angular/forms@13.0.0, @angular/router@13.0.0, @angular/platform-browser-dynamic@13.0.0.
```

In other projects, it says it can't find the packages.

**Comment by zehavibarak** [comment]
I'm experiencing this too. Would appreciate support for ng 13

**Comment by markwhitfeld** [comment]
I am actively working on this. Have been for the past 2 weeks. So many things changed in the npm package format at one time unfortunately with the release of Angular 13.
We have actually released NG13 support twice already and had to roll back due to issues with NG12 and other older projects.
Making steady progress and will drop a message here once we believe we have it fully resolved. 

Right now, you can use StackBlitz v2 (with WebContainers) to run your Angular 13 projects as a workaround to the current issue.

**Comment by zdrawku** [comment]
We are experiencing the same problem with our library, unfortunately even with the WebContainers usage the issue still remains - [Demo](https://stackblitz.com/edit/angular-i1jikx-bv1ygj?file=src%2Fstyles.scss)

This might be related to the turbo modules that are used in sass

**Comment by rvalitov** [comment]
Unfortunately I can't even run new Angular 12 projects. Only old saved Angular 12 projects work, but if I modify them, then the do not compile and do not work.

**Comment by markwhitfeld** [comment]
Hoping to release a fix soon, the issues we experienced with the initial attempts at a release with NG13 support were related to the fact that the new behavior needed to be rolled out on new uncached endpoint and some unreliable response times from the npm registry were causing some essential ngcc package calls to continually time out and never return correctly.
Will post here when we drop a new improved release supporting NG13.

**Comment by markwhitfeld** [comment]
@rvalitov Would it be possible to send some examples of your NG12 stackblitz projects that work and those that don't?
@zdrawku Do you have any non-webcontainer pre-NG13 projects that are failing?

**Comment by zdrawku** [comment]
> Do you have any non-webcontainer pre-NG13 projects that are failing?

If by saying Pre-NG13 you mean Angular 12, yes [this is such a project](https://stackblitz.com/edit/github-wcqean), but everything is working fine there (Angular 12.2.9, Ignite UI for Angular 12.1.6.

**Comment by markwhitfeld** [comment]
Ok, so this issue is all related to the new Angular package format which is used by any package built by Angular 13. The issue is not with the Ivy partial compilation, but the `exports` field in the `package.json` and the `mjs` file extension. The WebContainer team will be looking into the issue you are having there with the `sass` import. That is also related to the `exports` field used by the newly published version of `igniteui-angular` (built in NG13 package format).

**Comment by rvalitov** [comment]
@markwhitfeld 
Example is below:
https://stackblitz.com/edit/angular-5st1wc - it's an old project with Angular 12.2.9, and it works
Then I make a fork:
https://stackblitz.com/edit/angular-5st1wc-716apy - it also works, until I make changes to the dependencies list.
If I add any dependency, then it stops working. For example, I need to add `ngx-pipes`:
![image](https://user-images.githubusercontent.com/16267156/144241784-b4cc1411-4ee7-463b-8e47-599fdcb3c464.png)

After I add it, I see it in the list:
![image](https://user-images.githubusercontent.com/16267156/144241848-8753384c-f9d3-4805-8ea3-604ee5eb1daf.png)

Then, I see a missing dependency error:
![image](https://user-images.githubusercontent.com/16267156/144241926-8e742e18-581c-4f15-858d-9c4ab86b5cbb.png)

If I click install missing packages button, then it installs angular core 13:
![image](https://user-images.githubusercontent.com/16267156/144242130-ab0d44b2-a174-4a97-8f95-17e130a1cdfb.png)

And still shows missing packages error:
![image](https://user-images.githubusercontent.com/16267156/144242202-40cc538c-4ed3-425b-931b-71f39b84ebe9.png)


Another example are the examples from the [Taiga UI](https://github.com/TinkoffCreditSystems/taiga-ui) that are dependent on Angular 12.2.13, for example https://stackblitz.com/edit/kewp7s--run?file=src/app/app.component.ts
And also has the same issue:
![image](https://user-images.githubusercontent.com/16267156/144242743-12fd8f20-74e8-4432-a772-4c94c75bf294.png)

**Comment by markwhitfeld** [comment]
@zdrawku The issue you mentioned with WebContainer is in fact a separate issue that is caused by a node worker API that the Angular CLI is using which doesn't exist yet in WebContainer. Could you report your issue under the [webcontainer-core](https://github.com/stackblitz/webcontainer-core) repo so that it is visible and can be tracked & updated under that project?
PS. We are already working with the Angular team on a fix

**Comment by dobromirts** [comment]
@markwhitfeld are we going to be able to import sass modules in the current version without WebContainers when NG13 support is released, related also to this issue https://github.com/stackblitz/core/issues/1681

**Comment by Splaktar** [comment]
Whenever I try to fork an Angular v13 StackBlitz opened from https://material.angular.io, I get an HTTP 500 error from the StackBlitz API. I can't seem to make a sharable StackBlitz with Angular v13 at this time.

**Comment by markwhitfeld** [comment]
@dobromirts There is an Angular Cli PR in progress to fall back to the normal dart-sass approach when using WebContainers:
https://github.com/angular/angular-cli/pull/22294

**Comment by BenRacicot** [comment]
Hey @markwhitfeld, thanks for your work on this. 
Should we be watching this thread to be updated on Stackblitz / Angular 13 compat?

**Comment by markwhitfeld** [comment]
@benRacicot Yes. The fix is almost ready. Expecting it to land early next week.

**Comment by markwhitfeld** [comment]
Great news! Support for Angular 13 has finally rolled out.
Please post a message here if there are any major issues in your Angular 13 project.
For the next day or two (until 12 December), there is a possibility of an initial slow down in starting up the dev server or running NGCC (or potentially even timeouts) as the packages repopulate into the cache as they are used, but it should come right after a refresh or two if you do have any issues. Anything else should be reported as a new issue.
Thanks for your patience everyone!

**Comment by markwhitfeld** [comment]
@rvalitov This is a separate issue (the fact that the versions are unintentionally bumped to NG13). Would it be possible to submit this issue separately so that it can be tracked separately?
> @markwhitfeld Example is below: https://stackblitz.com/edit/angular-5st1wc - it's an old project with Angular 12.2.9, and it works Then I make a fork: https://stackblitz.com/edit/angular-5st1wc-716apy - it also works, until I make changes to the dependencies list. If I add any dependency, then it stops working. For example, I need to add `ngx-pipes`: ![image](https://user-images.githubusercontent.com/16267156/144241784-b4cc1411-4ee7-463b-8e47-599fdcb3c464.png)
> 
> After I add it, I see it in the list: ![image](https://user-images.githubusercontent.com/16267156/144241848-8753384c-f9d3-4805-8ea3-604ee5eb1daf.png)
> 
> Then, I see a missing dependency error: ![image](https://user-images.githubusercontent.com/16267156/144241926-8e742e18-581c-4f15-858d-9c4ab86b5cbb.png)
> 
> If I click install missing packages button, then it installs angular core 13: ![image](https://user-images.githubusercontent.com/16267156/144242130-ab0d44b2-a174-4a97-8f95-17e130a1cdfb.png)
> 
> And still shows missing packages error: ![image](https://user-images.githubusercontent.com/16267156/144242202-40cc538c-4ed3-425b-931b-71f39b84ebe9.png)
> 
> Another example are the examples from the [Taiga UI](https://github.com/TinkoffCreditSystems/taiga-ui) that are dependent on Angular 12.2.13, for example https://stackblitz.com/edit/kewp7s--run?file=src/app/app.component.ts And also has the same issue: ![image](https://user-images.githubusercontent.com/16267156/144242743-12fd8f20-74e8-4432-a772-4c94c75bf294.png)

**Comment by Totati** [comment]
When will the Angular starter use Angular 13?

**Comment by markwhitfeld** [comment]
Ok, so we released some fixes that should make NG13 more 'fully baked'. Especially when it comes to handling of sass resolution in ESM format packages. Please post here if there are any NG13 samples that are not working.

**Comment by wondie** [comment]
> Ok, so we released some fixes that should make NG13 more 'fully baked'. Especially when it comes to handling of sass resolution in ESM format packages. Please post here if there are any NG13 samples that are not working.
 I am still facing the issue. 
E.g. https://stackblitz.com/edit/kingsbury-jspdf-autotables-usecss-ia7zo9?file=src%2Fapp%2Fapp.component.ts

**Comment by amillerman01** [comment]
@markwhitfeld There still seems to be a problem with using NG13 material, where an error comes back saying 

> Missing "./fesm2015/material.mjs" export in "@angular/material" package

This happens if we use the custom theme options provided by angular material for NG13. Someone's logged it in much more detail here in #1792 but I thought it might be good to have referenced in this issue too. I've been running into this error all week and I can't make heads or tails of it unfortunately. Any help on this is hugely appreciated!
