### ISSUE TITLE
file not save correctly

### ISSUE THREAD

**Issue by suisuyy** [stackblitz/core#1757]
### Describe the bug

when i use ctrl+s to save file, it seems not save , the index.js not restart, nodmon not monitor the save, event i use cat index.js, it still show the old file, but when i reload the page, the file is update. this is huge problem

### Link to the blitz that caused the error

https://stackblitz.com/edit/runnode?file=index.js

### Steps to reproduce

1.change some text in index.js,
2.not rerun 
3.use cat index.js,still old content
4.reload page 
5.seems changed

### Expected behavior

it should save correctly

### Platform

```
Browser name  = Chrome 
Full version  = 95.0.4638.69
Major version = 95
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 Edg/95.0.1020.53
performance.memory = {
  "totalJSHeapSize": 68434616,
  "usedJSHeapSize": 65631260,
  "jsHeapSizeLimit": 4294705152
}
Hash = 6c82f838340a5d37c50f004ca724bcc8f75bc71c
```

**Comment by HeyGarrison** [comment]
This deals with our git functionality which is currently being re-worked with some of our other roadmap efforts. ❤️ 

So moving to the core repo since it's not a webcontainer issue.

**Comment by kc0tlh** [comment]
This issue is now resolved! Full writeup in Github issue #2473

**Comment by suisuyy** [comment]
yeah,currently stackbliz ide will pull from repo then overwrite local file on start. the new codeflow ide look very powerful,i need try it, thanks this is great

**Comment by suisuyy** [comment]
> 

oh,the new codeflow still same as old stackbliz, you cant save your work if you forgot commit to github, files will reset to last commit when open the ide,that not a good behavior

**Comment by kc0tlh** [comment]
@suisuyy I thought this had already shipped in VS Code as I know it's planned for the GA launch. Checking with the eng team. Will update you here when I hear back!

**Comment by samdenty** [comment]
@suisuyy we had basic persistence but that was recently removed as it was buggy - we're working on new improved persistence for launch

**Comment by suisuyy** [comment]
thanks,its amazing work to make vscode in browser, currently
 i can set up a auto commit when save , it works ok.
