### ISSUE TITLE
Offer a way to take full control of index.html

### ISSUE THREAD

**Issue by justinfagnani** [stackblitz/core#188]
I need to add script tags that run before the compiled app script hosted in a project. Currently there isn't a way because the index.html file is compiled and dynamically injected, including externally resources. These script tags run async, which means the timing is wrong.

See this example: https://stackblitz.com/edit/es6-xx1xcd?file=index.html which fails in Chrome (partially due to compiling out ES6 classes that really need to be ES6 classes).

The external resource https://unpkg.com/@webcomponents/webcomponentsjs@1.0.18/custom-elements-es5-adapter.js _needs_ to run before the project's js because it patches the environment, redefining HTMLElement. It runs, but not before the inlined index.js code and it's dependencies have.

I tried adding a `<script>` tag to index.html, but that didn't even run, presumably because of the way index.html content is injected into the page.

**Comment by Alucardz** [comment]
Full access to index.html would be awesome! Including the head tag ofc

**Comment by EricSimons** [comment]
This is now fixed! Simply place any scripts in the head tag in index.html :)

**Comment by justinfagnani** [comment]
Actually, I still can't get it working. It looks like script tags in index.html run after index.js, so I can't get the polyfill to load correctly.

See here: https://stackblitz.com/edit/js-ngbqk4?file=index.js

**Comment by EricSimons** [comment]
@justinfagnani just tweeted you back about this. Looks like you forgot to end the script tag src attr with a double quote- here's a fork I made w/ that fixed & dev server set to page reload instead of HMR: https://t.co/sMTUhFKEZu

**Comment by JosefJezek** [comment]
@EricSimons Not working after rename index.js.
https://stackblitz.com/edit/js-j1awgw?file=index.html
