### ISSUE TITLE
Auto-Import and code suggestions not functioning properly

### ISSUE THREAD

**Issue by mbechev** [stackblitz/core#3093]
### **Description of Bug**
In the Angular application, trying to use the `@ViewChild` decorator for example, doesn't auto import it anymore.
Instead, the decorator needs to be manually imported:

``` ts
import { ViewChild } from "@angular/core"
```

Another related issue is that if the `@ViewChild` decorator isn't imported, but used in the component, this part of the code isn't underlined as a problematic code. The only visual indication is the error message on the right:
<img width="1054" alt="image" src="https://github.com/user-attachments/assets/befc19c2-b205-4ff3-80c9-9e7ddbc8d870">

### **Steps to Reproduce**

1. Create any Angular application.
2. Try to import the `ViewChild` decorator (or anything else).
3. No code suggestions, auto-import, or underlying the code as incorrect.

### **Expected Behavior**
Before roughly a week this was functioning correctly. The user was able to auto-import modules and components and see where the problem came from.

**Comment by mbechev** [comment]
Is there any update on this issue?
cc @EricSimons @sulco @Nemikolh

**Comment by samdenty** [comment]
We recently updated to typescript@5.5.3 on july 12th which ties into when stuff started breaking for you

cc @SamVerschueren who did this upgrade

**Comment by SamVerschueren** [comment]
It seems to be working for me (https://stackblitz.com/~/edit/stackblitz-starters-ub2veq?file=src/main.ts).

![image](https://github.com/user-attachments/assets/9124d244-a439-4a5e-b988-f5a125ac1719)

Also if I don't import it, it shows the squigly lines.

![image](https://github.com/user-attachments/assets/8e4c813a-afb9-45a1-9698-9ff32aa602a9)

Do I need to do something first in order to break it?

**Comment by yanmariomenev** [comment]
@SamVerschueren  It seems that when the application is built with the web containers, it works, but the following will not work:
https://stackblitz.com/edit/angular-jsh172 (I used the same package.json and angular.json for the demo)

Or any of the examples from Kendo Angular - https://stackblitz.com/edit/angular-cpfgmu

![Screenshot 2024-08-02 at 15 23 50](https://github.com/user-attachments/assets/785e584b-62b9-4367-a6d2-be122f95cf68)

I hope this helps to pinpoint the issue.

**Comment by SamVerschueren** [comment]
Ooh interesting. Yes that information helps!

**Comment by samdenty** [comment]
Btw @SamVerschueren that link you said you couldn't reproduce on is the new editor (not classic)

**Comment by mikeandtherest** [comment]
In the last month or so, the import suggestions stopped working for us as well. Without them, Stackblitz is just too hard to use during our presentations. Any updates on a fix? Thanks!

**Comment by samdenty** [comment]
> In the last month or so, the import suggestions stopped working for us as well. Without them, Stackblitz is just too hard to use during our presentations. Any updates on a fix? Thanks!

@mikeandtherest you can use the new editor in meantime (it runs full vscode). Put a /~ before /edit ie. https://stackblitz.com/~/edit/node

**Comment by mikeandtherest** [comment]
I don't think that works. Whenever I add the /~/ part, it switches to /c/ and it leaves me on the current version of the editor.

https://stackblitz.com/~/edit/  -->  https://stackblitz.com/c/edit/

**Comment by samdenty** [comment]
@d3lm can you grant the new editor FF?

**Comment by d3lm** [comment]
Done.

**Comment by yanmariomenev** [comment]
@samdenty 
We've noticed that the issue is marked as completed, but the editor is still unchanged (IntelliSense is still not working). Does the fix need more time to go live, or are we missing something?

**Comment by samdenty** [comment]
Hi @yanmariomenev, I pinged @SamVerschueren to see if there was a fix and he mentioned one pr but I think that fixes something else. I see he has another pr open so I'll see if that can be merged

**Comment by yanmariomenev** [comment]
Today, I noticed that autocompletion suggestions are back and appear to be fixed based on my testing. This can be closed upon your inspection. :) Thanks for the fast response and fix.

**Comment by mbechev** [comment]
> Today, I noticed that autocompletion suggestions are back and appear to be fixed based on my testing. This can be closed upon your inspection. :) Thanks for the fast response and fix.

Confirm this. Thanks 👍🏽
