### ISSUE TITLE
Can't find package ""

### ISSUE THREAD

**Issue by inorganik** [stackblitz/core#724]
Hi, I'm trying to run the angular app in this [github repo](https://github.com/briebug/ngrx-demo) but I am getting "Can't find package" with no package name specified.

<img width="677" alt="screen shot 2018-10-10 at 1 38 17 pm" src="https://user-images.githubusercontent.com/109553/46768955-5a37a100-cca7-11e8-809a-5b3499a23485.png">

Initially I got an error about failed package installs that were actually import paths, so I replaced all the tsconfig paths with relative paths, and double checked all my import paths since stackblitz is looking there for dependencies. However they all look good. The app runs locally with no errors. All the dependencies in package.json are standard angular deps. Any idea what causes this error?

Here is the stackblitz link to repro: 

http://stackblitz.com/github/briebug/ngrx-demo

**Comment by apai4** [comment]
Sorry about this, @inorganik! This issue was caused by a bug in the way we handle lazy loaded routes in Angular, which made us improperly display a missing dependency error. I just pushed an update that should fix this, so lmk if you run into any more issues! We'll be supporting paths in tsconfig in the future as well, so once that's implemented on our end you'll be able to import modules via paths defined there without any modifications. Thanks for reporting this!

**Comment by inorganik** [comment]
No problem, thanks for the quick fix! I'm just glad that my issue wasn't a dumb mistake on my part. 😆

**Comment by hardikgondalia** [comment]
Any Resolution for it? I still facing issue in React Application

**Comment by ttathe** [comment]
I am still facing issue with Angular
